# Generated by Django 5.0.2 on 2024-06-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='dia',
            field=models.IntegerField(default=1),
        ),
    ]
