# Generated by Django 5.0.2 on 2024-06-04 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_lugar_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='dia',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='nota',
            field=models.TextField(max_length=50),
        ),
    ]
