# Generated by Django 5.0.2 on 2024-06-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_alter_lugar_dia_alter_preferencia_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectura',
            name='orden',
        ),
        migrations.AddField(
            model_name='cliente',
            name='orden',
            field=models.IntegerField(default='06'),
            preserve_default=False,
        ),
    ]
