# Generated by Django 5.0.2 on 2024-06-06 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_remove_lectura_orden_cliente_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='lectura',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='preferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='control.preferencia'),
        ),
    ]
