# Generated by Django 5.0.2 on 2024-06-06 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_alter_lectura_lectura_alter_lugar_preferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='preferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.preferencia'),
        ),
    ]
