# Generated by Django 5.0.2 on 2024-06-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_alter_lugar_preferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencia',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
