# Generated by Django 5.0.2 on 2024-06-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_alter_preferencia_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='medidor',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='imagen',
            field=models.ImageField(default='preferencias/default.png', upload_to='preferencias'),
        ),
    ]
