# Generated by Django 5.0.2 on 2024-06-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_alter_cliente_medidor_alter_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencia',
            name='nota',
            field=models.TextField(max_length=30),
        ),
    ]
