# Generated by Django 5.0.2 on 2024-06-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_alter_preferencia_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencia',
            name='nota',
            field=models.TextField(max_length=50),
        ),
    ]
