# Generated by Django 5.0.2 on 2024-10-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_alter_preferencia_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='lectura_anterior',
            field=models.IntegerField(default=0),
        ),
    ]
