# Generated by Django 5.0.2 on 2024-10-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_lectura_lectura_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
