# Generated by Django 5.0.2 on 2024-10-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_lectura_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='valor',
            field=models.IntegerField(default=350),
        ),
    ]
