# Generated by Django 5.0.2 on 2024-10-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_lugar_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='created_by',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
