# Generated by Django 5.0.2 on 2024-12-02 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
