# Generated by Django 5.0.2 on 2024-12-12 18:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0020_alter_solicitudes_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solicitudes',
            new_name='Solicitud',
        ),
    ]
