# Generated by Django 5.0.2 on 2024-12-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0023_alter_solicitud_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='lecturas'),
        ),
        migrations.AddField(
            model_name='lectura',
            name='observacion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
