# Generated by Django 5.0.2 on 2025-01-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0026_remove_lugar_preferencia_alter_lectura_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectura',
            name='observacion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_lectura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
