# Generated by Django 5.0.2 on 2025-02-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0027_remove_lectura_observacion_cliente_fecha_lectura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectura',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='lecturas',
            field=models.ManyToManyField(blank=True, to='control.lectura'),
        ),
    ]
