# Generated by Django 5.0.2 on 2025-02-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0028_remove_lectura_cliente_cliente_lecturas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='lecturas',
        ),
        migrations.AddField(
            model_name='lectura',
            name='cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
