# Generated by Django 5.0.2 on 2025-02-03 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0029_remove_cliente_lecturas_lectura_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectura',
            old_name='cliente',
            new_name='clientes',
        ),
    ]
