# Generated by Django 5.0.2 on 2025-02-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0030_rename_cliente_lectura_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='lecturas',
            field=models.ManyToManyField(blank=True, to='control.lectura'),
        ),
    ]
