# Generated by Django 5.0.2 on 2025-02-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0031_cliente_lecturas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectura',
            name='clientes',
        ),
    ]
