# Generated by Django 5.0.2 on 2025-02-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0033_remove_cliente_lecturas_cliente_ultima_lectura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_lectura',
        ),
    ]
