# Generated by Django 5.0.2 on 2025-02-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0034_remove_cliente_fecha_lectura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='metros',
        ),
    ]
