# Generated by Django 5.0.2 on 2025-02-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0035_remove_cliente_metros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectura',
            old_name='fecha',
            new_name='fecha_lectura',
        ),
    ]
