# Generated by Django 5.0.2 on 2025-02-11 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0036_rename_fecha_lectura_fecha_lectura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='control.lugar'),
        ),
    ]
