# Generated by Django 5.0.2 on 2025-03-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0038_remove_lectura_pagado_pago_lectura_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='observacion',
        ),
    ]
