# Generated by Django 5.0.2 on 2025-03-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0039_remove_pago_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
