# Generated by Django 5.0.2 on 2025-03-24 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0040_pago_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='lectura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='control.lectura'),
        ),
    ]
