# Generated by Django 5.0.2 on 2025-03-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0041_pago_lectura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='observacion',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
