# Generated by Django 5.0.2 on 2025-05-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0042_alter_pago_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
