# Generated by Django 5.2.2 on 2025-06-15 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0043_cliente_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='metros',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
