# Generated by Django 5.2.2 on 2025-06-15 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0044_cliente_metros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='metros',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
