# Generated by Django 5.2.2 on 2025-07-14 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0045_alter_cliente_metros'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='moratorio',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='lectura',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
