# Generated by Django 5.2.2 on 2025-07-19 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0047_alter_lectura_created_by_alter_pago_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas', to='control.pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='lectura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pago_relacionado', to='control.lectura'),
        ),
    ]
